all: category_theory_refcard.tex
	dia -e figures/plongement.eps -t eps figures/plongement.dia
	pdflatex category_theory_refcard.tex
	rm -f category_theory_refcard.log
	rm -f category_theory_refcard.aux
	rm -f texput.log
